[package]
name = "AstroForge"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", default-features = false, features = ["bevy_asset", "bevy_winit", "bevy_pbr", "x11", "wayland"] }
